[package]
name = "remotia-core-codecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remotia-core = { path = "../remotia-core" }
async-trait = "0.1.68"
bytes = "1.4.0"
