[workspace]
resolver = "2"

members = [
    "remotia",
    "remotia-buffer-utils",
    "remotia-samples",
    "remotia-core-capturers",
    "remotia-ffmpeg-codecs",
    "remotia-srt",
    "remotia-core-renderers",
    "remotia-core-loggers",
]
