[workspace]
resolver = "2"

members = [
    "remotia",

    "remotia-core",
    "remotia-buffer-utils",
    "remotia-profilation-utils",

    "remotia-samples",

    "remotia-core-capturers",
    "remotia-core-codecs",
    "remotia-core-renderers",
    "remotia-core-loggers",

    "remotia-ffmpeg-codecs",
    "remotia-srt",

    "paper-experiments"
]
