[package]
name = "remotia"
version = "0.1.0"
authors = ["Lorenzo Catania <aegroto@protonmail.com>"]
edition = "2021"

[dependencies.tokio]
version = '0.2'
features = [
    'udp',
    'sync',
    'rt-core',
    'io-util',
]

[dev-dependencies]
tokio-openssl = '0.4'
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies.tokio]
version = '0.2'
features = [
    'time',
    'macros',
]

[dependencies]
scrap = "0.5"
pixels = "0.7.0"
# beryllium = { version = "0.3.2", features = ["extern_crate_raw_window_handle"] }
zstring = "0.1.2"
beryllium = { git = "https://github.com/Lokathor/beryllium.git", rev = "9375bbd2dbc8c35d5f669181a9d525315f20ba40", features = ["extern_crate_raw_window_handle"] }
thiserror = "1.0.30"
rsmpeg = "0.6.0"
cstr = "0.2.9"
rgb2yuv420 = "0.2.3"
yuv = "0.1.4"
